services:
  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--requirepass", "mypassword"]
    ports:
      - 6379:6379
    environment:
      - REDIS_PASSWORD=mypassword
    networks:
      - myNetwork

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    command: >
      elasticsearch
      -E logger.level=ERROR    
    ports:
      - "9200:9200"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - myNetwork

  octoxlabs:
    build:
      context: ./octoxlabs
      dockerfile: ./Dockerfile
    image: octoxlabs
    container_name: octoxlabs
    privileged: true
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    volumes:
      - ./octoxlabs:/app
      - "./data/root:/root"
    ports:
      - "8000:8000"
    depends_on:
      - redis
    networks:
      - myNetwork

  worker:
    build: ./worker
    command: python worker.py
    container_name: worker
    volumes:
      - ./worker:/app
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=mypassword 
      - ELASTICSEARCH_HOST=elasticsearch
      - ELASTICSEARCH_PORT=9200
    networks:
      - myNetwork

volumes:
  es_data:

networks:
  myNetwork:
    name: myNetwork
    driver: bridge
