version: '3'

services:
  redis:
    image: redis:alpine

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.1
    environment:
      - discovery.type=single-node

  django_app:
    build: ./django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./django_app:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - elasticsearch

  worker:
    build: ./worker
    command: python worker.py
    depends_on:
      - redis
      - elasticsearch

volumes:
  postgres_data: